<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\banco\controllers;

use gamboamartin\banco\models\bn_sucursal_cuenta;
use gamboamartin\errores\errores;
use gamboamartin\organigrama\html\org_sucursal_html;
use gamboamartin\template\html;
use html\bn_banco_html;
use html\bn_sucursal_cuenta_html;
use PDO;
use stdClass;

class controlador_bn_sucursal_cuenta extends _base_sin_cod {

    public array|stdClass $keys_selects = array();

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){
        $modelo = new bn_sucursal_cuenta(link: $link);
        $html_ = new bn_sucursal_cuenta_html(html: $html);
        parent::__construct(html_: $html_,link:  $link,modelo:  $modelo, paths_conf: $paths_conf);
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta($header, $ws);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template', data: $r_alta, header: $header,ws:  $ws);
        }

        $org_sucursal_id = (new org_sucursal_html(html: $this->html_base))->select_org_sucursal_id(
            cols: 12,con_registros: true,id_selected: -1,link:  $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $org_sucursal_id, header: $header,ws:  $ws);
        }
        $this->inputs->org_sucursal_id = $org_sucursal_id;

        $bn_banco_id = (new bn_banco_html(html: $this->html_base))->select_bn_banco_id(
            cols: 12,con_registros: true,id_selected: -1,link:  $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $bn_banco_id, header: $header,ws:  $ws);
        }
        $this->inputs->bn_banco_id = $bn_banco_id;

        $num_cuenta = (new bn_sucursal_cuenta_html(html: $this->html_base))->input(cols: 12,row_upd:  new stdClass(),
             name: 'num_cuenta',place_holder: 'Numero de cuenta',value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $num_cuenta, header: $header,ws:  $ws);
        }
        $this->inputs->num_cuenta = $num_cuenta;

        $clabe = (new bn_sucursal_cuenta_html(html: $this->html_base))->input(cols: 12,row_upd:  new stdClass(),
            name: 'clabe',place_holder: 'clabe',value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $clabe, header: $header,ws:  $ws);
        }
        $this->inputs->clabe = $clabe;

        return $r_alta;
    }

    public function init_datatable(): stdClass
    {
        $datatables = new stdClass();
        $datatables->columns = array();
        $datatables->columns['bn_sucursal_cuenta_id']['titulo'] = 'Id';
        $datatables->columns['org_empresa_rfc']['titulo'] = 'RFC';
        $datatables->columns['org_empresa_razon_social']['titulo'] = 'Empresa';
        $datatables->columns['bn_banco_descripcion']['titulo'] = 'Banco';

        $datatables->filtro = array();
        $datatables->filtro[] = 'bn_sucursal_cuenta.id';
        $datatables->filtro[] = 'org_empresa.rfc';
        $datatables->filtro[] = 'org_empresa.razon_social';

        return $datatables;
    }

    public function modifica(bool $header, bool $ws = false, array $keys_selects = array()): array|stdClass
    {
        $r_modifica = parent::modifica($header, $ws, $keys_selects); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template', data: $r_modifica, header: $header,ws:  $ws);
        }

        $org_sucursal_id = (new org_sucursal_html(html: $this->html_base))->select_org_sucursal_id(
            cols: 12,con_registros: true,id_selected: $this->row_upd->org_sucursal_id,link:  $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $org_sucursal_id, header: $header,ws:  $ws);
        }
        $this->inputs->org_sucursal_id = $org_sucursal_id;

        $bn_banco_id = (new bn_banco_html(html: $this->html_base))->select_bn_banco_id(
            cols: 12,con_registros: true,id_selected: $this->row_upd->bn_banco_id,link:  $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $bn_banco_id, header: $header,ws:  $ws);
        }
        $this->inputs->bn_banco_id = $bn_banco_id;

        $num_cuenta = (new bn_sucursal_cuenta_html(html: $this->html_base))->input(cols: 12,row_upd:  $this->row_upd,
            name: 'num_cuenta',place_holder: 'Numero de cuenta',value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $num_cuenta, header: $header,ws:  $ws);
        }
        $this->inputs->num_cuenta = $num_cuenta;

        $clabe = (new bn_sucursal_cuenta_html(html: $this->html_base))->input(cols: 12,row_upd:  $this->row_upd,
            name: 'clabe',place_holder: 'clabe',value_vacio:  false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input', data: $clabe, header: $header,ws:  $ws);
        }
        $this->inputs->clabe = $clabe;

        return $r_modifica;
    }
}
